// Generated by test/extract_spreadsheet.py. Do not edit by hand.
export default {
 "source": "NFL Skins League (01.25.26)_v1.xlsx",
 "note": "The workbook holds no game scores. Base skins are the workbook's own 0/1 values; bonus skins are synthesised from the workbook's per-team weekly bonus totals, spread across that team's scoring picks. Per-pick bonus attribution is therefore synthetic; per-team weekly and season totals are not.",
 "problems": [],
 "state": {
  "version": 1,
  "settings": {
   "skinValue": 100,
   "bonusEnabledByWeek": {
    "1": true,
    "2": true,
    "3": true,
    "4": true,
    "5": true,
    "6": true,
    "7": true,
    "8": true,
    "9": true,
    "10": true,
    "11": true,
    "12": true,
    "13": true,
    "14": true,
    "15": true,
    "16": true,
    "17": true,
    "18": true,
    "WC": true,
    "DIV": true,
    "CC": true,
    "SB": true
   }
  },
  "results": {
   "2": {
    "Eagles-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Giants-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "49ers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Patriots-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Seahawks-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Bills-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Colts-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Panthers-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Broncos-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jaguars-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Ravens-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Texans-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Titans-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Cowboys-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Dolphins-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Chiefs-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jets-L": {
     "result": "L",
     "pointsFor": 6,
     "pointsAgainst": 20
    },
    "Bengals-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Packers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Falcons-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Lions-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Browns-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Chargers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Raiders-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Commanders-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Saints-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Buccaneers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Rams-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Cardinals-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    }
   },
   "3": {
    "Eagles-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Giants-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "49ers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Patriots-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Seahawks-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Bills-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Colts-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Panthers-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Broncos-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jaguars-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Ravens-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Texans-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Titans-L": {
     "result": "L",
     "pointsFor": 6,
     "pointsAgainst": 20
    },
    "Cowboys-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Dolphins-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Chiefs-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Jets-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Bengals-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Packers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Lions-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Browns-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Chargers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Raiders-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Commanders-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Saints-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Buccaneers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Rams-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Cardinals-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    }
   },
   "4": {
    "Eagles-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Giants-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "49ers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Patriots-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Seahawks-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Bills-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Colts-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Panthers-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Broncos-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Jaguars-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Ravens-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Texans-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Titans-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Cowboys-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Dolphins-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Chiefs-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Jets-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Bengals-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Packers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Lions-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Browns-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Chargers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Raiders-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Commanders-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Saints-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Buccaneers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Rams-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Cardinals-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    }
   },
   "5": {
    "Eagles-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Giants-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "49ers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Patriots-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Seahawks-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Bills-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Colts-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Panthers-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Broncos-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Jaguars-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Ravens-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Texans-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Titans-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Cowboys-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Dolphins-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Chiefs-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jets-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Bengals-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Packers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Lions-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Browns-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Chargers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Raiders-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Commanders-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Saints-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Buccaneers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Rams-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Cardinals-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    }
   },
   "6": {
    "Eagles-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Giants-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "49ers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Patriots-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Seahawks-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Bills-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Colts-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Panthers-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Broncos-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Jaguars-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Ravens-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Texans-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Titans-L": {
     "result": "L",
     "pointsFor": 6,
     "pointsAgainst": 20
    },
    "Cowboys-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Dolphins-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Chiefs-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Jets-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Bengals-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Packers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Falcons-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Lions-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Browns-L": {
     "result": "L",
     "pointsFor": 6,
     "pointsAgainst": 20
    },
    "Chargers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Raiders-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Falcons-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Commanders-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Saints-L": {
     "result": "L",
     "pointsFor": 6,
     "pointsAgainst": 20
    },
    "Buccaneers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Rams-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Cardinals-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    }
   },
   "7": {
    "Eagles-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Giants-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "49ers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Patriots-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Seahawks-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Bills-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Colts-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Panthers-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Broncos-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Jaguars-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Ravens-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Texans-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Titans-L": {
     "result": "L",
     "pointsFor": 6,
     "pointsAgainst": 20
    },
    "Cowboys-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Dolphins-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Chiefs-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Jets-L": {
     "result": "L",
     "pointsFor": 6,
     "pointsAgainst": 20
    },
    "Bengals-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Packers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Falcons-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Lions-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Browns-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Chargers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Raiders-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Commanders-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Saints-L": {
     "result": "L",
     "pointsFor": 6,
     "pointsAgainst": 20
    },
    "Buccaneers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Rams-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Cardinals-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    }
   },
   "8": {
    "Eagles-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Giants-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "49ers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Patriots-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Seahawks-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Bills-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Colts-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Panthers-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Broncos-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Jaguars-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Ravens-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Texans-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Titans-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Cowboys-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Dolphins-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Chiefs-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Jets-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Bengals-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Packers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Falcons-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Lions-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Browns-L": {
     "result": "L",
     "pointsFor": 6,
     "pointsAgainst": 20
    },
    "Chargers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Raiders-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Falcons-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Commanders-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Saints-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Buccaneers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Rams-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Cardinals-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    }
   },
   "9": {
    "Eagles-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Giants-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "49ers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Patriots-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Seahawks-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Bills-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Colts-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Panthers-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Broncos-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Jaguars-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Ravens-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Texans-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Titans-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Cowboys-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Dolphins-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Chiefs-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jets-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Bengals-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Packers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Lions-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Browns-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Chargers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Raiders-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Commanders-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Saints-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Buccaneers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Rams-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Cardinals-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    }
   },
   "10": {
    "Eagles-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Giants-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "49ers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Patriots-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Seahawks-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Bills-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Colts-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Panthers-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Broncos-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Jaguars-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Ravens-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Texans-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Titans-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Cowboys-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Dolphins-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Chiefs-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jets-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Bengals-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Packers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Lions-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Browns-L": {
     "result": "L",
     "pointsFor": 6,
     "pointsAgainst": 20
    },
    "Chargers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Raiders-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Commanders-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Saints-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Buccaneers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Rams-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Cardinals-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    }
   },
   "11": {
    "Eagles-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Giants-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "49ers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Patriots-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Seahawks-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Bills-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Colts-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Panthers-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Broncos-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Jaguars-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Ravens-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Texans-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Titans-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Cowboys-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Dolphins-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Chiefs-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jets-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Bengals-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Packers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Falcons-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Lions-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Browns-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Chargers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Raiders-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Commanders-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Saints-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Buccaneers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Rams-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Cardinals-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    }
   },
   "12": {
    "Eagles-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Giants-L": {
     "result": "L",
     "pointsFor": 6,
     "pointsAgainst": 20
    },
    "49ers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Patriots-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Seahawks-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Bills-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Colts-L": {
     "result": "L",
     "pointsFor": 6,
     "pointsAgainst": 20
    },
    "Panthers-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Broncos-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jaguars-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Ravens-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Texans-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Titans-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Cowboys-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Dolphins-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Chiefs-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Jets-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Bengals-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Packers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Falcons-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Lions-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Browns-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Chargers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Raiders-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Commanders-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Saints-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Buccaneers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Rams-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Cardinals-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    }
   },
   "13": {
    "Eagles-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Giants-L": {
     "result": "L",
     "pointsFor": 6,
     "pointsAgainst": 20
    },
    "49ers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Patriots-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Seahawks-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Bills-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Colts-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Panthers-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Broncos-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Jaguars-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Ravens-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Texans-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Titans-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Cowboys-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Dolphins-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Chiefs-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jets-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Bengals-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Packers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Falcons-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Lions-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Browns-L": {
     "result": "L",
     "pointsFor": 6,
     "pointsAgainst": 20
    },
    "Chargers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Raiders-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Commanders-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Saints-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Buccaneers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Rams-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Cardinals-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    }
   },
   "14": {
    "Eagles-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Giants-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "49ers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Patriots-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Seahawks-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Bills-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Colts-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Panthers-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Broncos-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Jaguars-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Ravens-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Texans-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Titans-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Cowboys-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Dolphins-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Chiefs-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jets-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Bengals-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Packers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Falcons-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Lions-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Browns-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Chargers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Raiders-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Commanders-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Saints-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Buccaneers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Rams-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Cardinals-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    }
   },
   "15": {
    "Eagles-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Giants-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "49ers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Patriots-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Seahawks-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Bills-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Colts-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Panthers-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Broncos-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Jaguars-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Ravens-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Texans-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Titans-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Cowboys-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Dolphins-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Chiefs-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jets-L": {
     "result": "L",
     "pointsFor": 6,
     "pointsAgainst": 20
    },
    "Bengals-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Packers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Lions-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Browns-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Chargers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Raiders-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Commanders-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Saints-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Buccaneers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Rams-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Cardinals-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    }
   },
   "16": {
    "Eagles-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Giants-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "49ers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Patriots-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Seahawks-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Bills-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Colts-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Panthers-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Broncos-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jaguars-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Ravens-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Texans-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Titans-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Cowboys-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Dolphins-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Chiefs-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jets-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Bengals-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Packers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Lions-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Browns-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Chargers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Raiders-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Commanders-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Saints-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Buccaneers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Rams-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Cardinals-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    }
   },
   "17": {
    "Eagles-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Giants-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "49ers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Patriots-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Seahawks-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Bills-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Colts-L": {
     "result": "L",
     "pointsFor": 6,
     "pointsAgainst": 20
    },
    "Panthers-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Broncos-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Jaguars-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Ravens-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Texans-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Titans-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Cowboys-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Dolphins-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Chiefs-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jets-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Bengals-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Packers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Lions-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Browns-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Chargers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Raiders-L": {
     "result": "L",
     "pointsFor": 6,
     "pointsAgainst": 20
    },
    "Falcons-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Commanders-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Saints-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Buccaneers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Rams-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Cardinals-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    }
   },
   "18": {
    "Eagles-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Giants-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "49ers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Patriots-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Seahawks-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Bills-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Colts-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Panthers-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Broncos-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Jaguars-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Ravens-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Texans-W": {
     "result": "W",
     "pointsFor": 42,
     "pointsAgainst": 6
    },
    "Titans-L": {
     "result": "L",
     "pointsFor": 6,
     "pointsAgainst": 20
    },
    "Cowboys-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Dolphins-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Chiefs-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jets-L": {
     "result": "L",
     "pointsFor": 6,
     "pointsAgainst": 20
    },
    "Bengals-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Packers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Lions-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Browns-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Chargers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Raiders-L": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Falcons-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Commanders-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Saints-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Buccaneers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Rams-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Cardinals-L": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    }
   },
   "WC": {
    "Eagles-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Giants-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "49ers-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Patriots-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Seahawks-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Bills-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Colts-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Panthers-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Broncos-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jaguars-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Ravens-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Texans-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 9
    },
    "Titans-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Cowboys-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Dolphins-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Chiefs-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jets-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Bengals-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Packers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Lions-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Browns-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Chargers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Raiders-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Falcons-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Commanders-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Saints-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Buccaneers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Rams-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Cardinals-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    }
   },
   "DIV": {
    "Eagles-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Giants-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "49ers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Patriots-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Seahawks-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Bills-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Colts-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Panthers-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Broncos-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Jaguars-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Ravens-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Texans-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Titans-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Cowboys-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Dolphins-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Chiefs-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jets-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Bengals-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Packers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Lions-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Browns-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Chargers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Raiders-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Falcons-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Commanders-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Saints-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Buccaneers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Rams-W": {
     "result": "W",
     "pointsFor": 20,
     "pointsAgainst": 17
    },
    "Cardinals-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    }
   },
   "CC": {
    "Eagles-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Giants-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "49ers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Patriots-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Seahawks-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Bills-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Colts-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Panthers-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Broncos-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jaguars-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Ravens-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Texans-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Titans-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Cowboys-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Dolphins-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Chiefs-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jets-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Bengals-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Packers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Lions-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Browns-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Chargers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Raiders-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Falcons-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Commanders-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Saints-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Buccaneers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Rams-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Cardinals-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    }
   },
   "SB": {
    "Eagles-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Giants-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "49ers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Patriots-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Seahawks-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Bills-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Colts-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Panthers-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Broncos-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jaguars-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Ravens-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Texans-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Titans-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Cowboys-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Dolphins-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Chiefs-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Jets-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Bengals-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Packers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Falcons-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Lions-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Browns-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Chargers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Raiders-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Falcons-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Commanders-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Saints-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    },
    "Buccaneers-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Rams-W": {
     "result": "L",
     "pointsFor": 17,
     "pointsAgainst": 20
    },
    "Cardinals-L": {
     "result": "L",
     "pointsFor": 3,
     "pointsAgainst": 45
    }
   }
  }
 },
 "expected": {
  "season": {
   "duriez": {
    "base": 52,
    "bonus": 16,
    "total": 68
   },
   "alec": {
    "base": 47,
    "bonus": 17,
    "total": 64
   },
   "joe": {
    "base": 51,
    "bonus": 23,
    "total": 74
   },
   "cummiskey": {
    "base": 41,
    "bonus": 18,
    "total": 59
   },
   "little": {
    "base": 52,
    "bonus": 24,
    "total": 76
   },
   "corley": {
    "base": 48,
    "bonus": 18,
    "total": 66
   }
  },
  "byWeek": {
   "duriez": {
    "1": 0,
    "2": 5,
    "3": 4,
    "4": 3,
    "5": 4,
    "6": 1,
    "7": 5,
    "8": 3,
    "9": 3,
    "10": 4,
    "11": 7,
    "12": 4,
    "13": 4,
    "14": 0,
    "15": 4,
    "16": 5,
    "17": 6,
    "18": 2,
    "WC": 3,
    "DIV": 1,
    "CC": 0,
    "SB": 0
   },
   "alec": {
    "1": 0,
    "2": 4,
    "3": 1,
    "4": 6,
    "5": 1,
    "6": 2,
    "7": 3,
    "8": 8,
    "9": 3,
    "10": 5,
    "11": 3,
    "12": 3,
    "13": 3,
    "14": 3,
    "15": 4,
    "16": 3,
    "17": 4,
    "18": 6,
    "WC": 1,
    "DIV": 1,
    "CC": 0,
    "SB": 0
   },
   "joe": {
    "1": 0,
    "2": 4,
    "3": 4,
    "4": 4,
    "5": 4,
    "6": 4,
    "7": 3,
    "8": 5,
    "9": 6,
    "10": 2,
    "11": 3,
    "12": 4,
    "13": 3,
    "14": 4,
    "15": 7,
    "16": 4,
    "17": 4,
    "18": 7,
    "WC": 2,
    "DIV": 0,
    "CC": 0,
    "SB": 0
   },
   "cummiskey": {
    "1": 0,
    "2": 4,
    "3": 5,
    "4": 2,
    "5": 1,
    "6": 4,
    "7": 8,
    "8": 5,
    "9": 1,
    "10": 1,
    "11": 3,
    "12": 5,
    "13": 3,
    "14": 5,
    "15": 2,
    "16": 4,
    "17": 4,
    "18": 2,
    "WC": 0,
    "DIV": 0,
    "CC": 0,
    "SB": 0
   },
   "little": {
    "1": 0,
    "2": 10,
    "3": 4,
    "4": 6,
    "5": 5,
    "6": 4,
    "7": 4,
    "8": 3,
    "9": 2,
    "10": 7,
    "11": 2,
    "12": 5,
    "13": 4,
    "14": 5,
    "15": 6,
    "16": 4,
    "17": 3,
    "18": 2,
    "WC": 0,
    "DIV": 0,
    "CC": 0,
    "SB": 0
   },
   "corley": {
    "1": 0,
    "2": 3,
    "3": 6,
    "4": 3,
    "5": 4,
    "6": 5,
    "7": 4,
    "8": 4,
    "9": 4,
    "10": 4,
    "11": 3,
    "12": 5,
    "13": 3,
    "14": 4,
    "15": 5,
    "16": 1,
    "17": 1,
    "18": 5,
    "WC": 1,
    "DIV": 1,
    "CC": 0,
    "SB": 0
   }
  },
  "picks": {
   "Raiders-L": {
    "base": 14,
    "bonus": 9,
    "total": 23
   },
   "Jets-L": {
    "base": 13,
    "bonus": 9,
    "total": 22
   },
   "Titans-L": {
    "base": 13,
    "bonus": 6,
    "total": 19
   },
   "Patriots-W": {
    "base": 14,
    "bonus": 5,
    "total": 19
   },
   "Rams-W": {
    "base": 11,
    "bonus": 7,
    "total": 18
   },
   "Cardinals-L": {
    "base": 14,
    "bonus": 4,
    "total": 18
   },
   "Texans-W": {
    "base": 12,
    "bonus": 6,
    "total": 18
   },
   "Bills-W": {
    "base": 11,
    "bonus": 6,
    "total": 17
   },
   "Broncos-W": {
    "base": 13,
    "bonus": 4,
    "total": 17
   },
   "Browns-L": {
    "base": 11,
    "bonus": 5,
    "total": 16
   },
   "49ers-W": {
    "base": 11,
    "bonus": 5,
    "total": 16
   },
   "Giants-L": {
    "base": 12,
    "bonus": 2,
    "total": 14
   },
   "Lions-W": {
    "base": 9,
    "bonus": 5,
    "total": 14
   },
   "Saints-L": {
    "base": 10,
    "bonus": 4,
    "total": 14
   },
   "Panthers-L": {
    "base": 8,
    "bonus": 6,
    "total": 14
   },
   "Chargers-W": {
    "base": 10,
    "bonus": 3,
    "total": 13
   },
   "Eagles-W": {
    "base": 10,
    "bonus": 3,
    "total": 13
   },
   "Ravens-W": {
    "base": 8,
    "bonus": 5,
    "total": 13
   },
   "Dolphins-L": {
    "base": 9,
    "bonus": 4,
    "total": 13
   },
   "Falcons-L": {
    "base": 8,
    "bonus": 4,
    "total": 12
   },
   "Cowboys-L": {
    "base": 8,
    "bonus": 2,
    "total": 10
   },
   "Falcons-W": {
    "base": 8,
    "bonus": 2,
    "total": 10
   },
   "Colts-L": {
    "base": 9,
    "bonus": 1,
    "total": 10
   },
   "Chiefs-W": {
    "base": 6,
    "bonus": 3,
    "total": 9
   },
   "Packers-W": {
    "base": 8,
    "bonus": 1,
    "total": 9
   },
   "Buccaneers-W": {
    "base": 7,
    "bonus": 1,
    "total": 8
   },
   "Bengals-W": {
    "base": 6,
    "bonus": 1,
    "total": 7
   },
   "Commanders-W": {
    "base": 4,
    "bonus": 2,
    "total": 6
   },
   "Jaguars-L": {
    "base": 4,
    "bonus": 1,
    "total": 5
   },
   "Seahawks-L": {
    "base": 2,
    "bonus": 0,
    "total": 2
   }
  },
  "draft": {
   "Raiders-L": {
    "team": "little",
    "pickNo": 20,
    "round": 4
   },
   "Jets-L": {
    "team": "cummiskey",
    "pickNo": 9,
    "round": 2
   },
   "Titans-L": {
    "team": "joe",
    "pickNo": 15,
    "round": 3
   },
   "Patriots-W": {
    "team": "duriez",
    "pickNo": 24,
    "round": 4
   },
   "Rams-W": {
    "team": "corley",
    "pickNo": 19,
    "round": 4
   },
   "Cardinals-L": {
    "team": "corley",
    "pickNo": 30,
    "round": 5
   },
   "Texans-W": {
    "team": "joe",
    "pickNo": 10,
    "round": 2
   },
   "Bills-W": {
    "team": "alec",
    "pickNo": 2,
    "round": 1
   },
   "Broncos-W": {
    "team": "alec",
    "pickNo": 23,
    "round": 4
   },
   "Browns-L": {
    "team": "little",
    "pickNo": 8,
    "round": 2
   },
   "49ers-W": {
    "team": "duriez",
    "pickNo": 13,
    "round": 3
   },
   "Giants-L": {
    "team": "duriez",
    "pickNo": 12,
    "round": 2
   },
   "Lions-W": {
    "team": "little",
    "pickNo": 5,
    "round": 1
   },
   "Saints-L": {
    "team": "corley",
    "pickNo": 7,
    "round": 2
   },
   "Panthers-L": {
    "team": "alec",
    "pickNo": 14,
    "round": 3
   },
   "Chargers-W": {
    "team": "little",
    "pickNo": 17,
    "round": 3
   },
   "Eagles-W": {
    "team": "duriez",
    "pickNo": 1,
    "round": 1
   },
   "Ravens-W": {
    "team": "joe",
    "pickNo": 3,
    "round": 1
   },
   "Dolphins-L": {
    "team": "joe",
    "pickNo": 27,
    "round": 5
   },
   "Falcons-L": {
    "team": "cummiskey",
    "pickNo": 28,
    "round": 5
   },
   "Cowboys-L": {
    "team": "joe",
    "pickNo": 22,
    "round": 4
   },
   "Falcons-W": {
    "team": "little",
    "pickNo": 29,
    "round": 5
   },
   "Colts-L": {
    "team": "alec",
    "pickNo": 16,
    "round": 2
   },
   "Chiefs-W": {
    "team": "cummiskey",
    "pickNo": 4,
    "round": 1
   },
   "Packers-W": {
    "team": "cummiskey",
    "pickNo": 26,
    "round": 4
   },
   "Buccaneers-W": {
    "team": "corley",
    "pickNo": 18,
    "round": 3
   },
   "Bengals-W": {
    "team": "cummiskey",
    "pickNo": 16,
    "round": 3
   },
   "Commanders-W": {
    "team": "corley",
    "pickNo": 6,
    "round": 1
   },
   "Jaguars-L": {
    "team": "alec",
    "pickNo": 26,
    "round": 5
   },
   "Seahawks-L": {
    "team": "duriez",
    "pickNo": 25,
    "round": 5
   }
  },
  "mendoza": 67.83333333333333,
  "skinValue": 100
 },
 "week1": {
  "results": {
   "Eagles-W": {
    "result": "W",
    "pointsFor": 20,
    "pointsAgainst": 17
   },
   "Giants-L": {
    "result": "L",
    "pointsFor": 17,
    "pointsAgainst": 20
   },
   "49ers-W": {
    "result": "W",
    "pointsFor": 20,
    "pointsAgainst": 17
   },
   "Patriots-W": {
    "result": "L",
    "pointsFor": 17,
    "pointsAgainst": 20
   },
   "Seahawks-L": {
    "result": "L",
    "pointsFor": 17,
    "pointsAgainst": 20
   },
   "Bills-W": {
    "result": "W",
    "pointsFor": 20,
    "pointsAgainst": 17
   },
   "Colts-L": {
    "result": "W",
    "pointsFor": 20,
    "pointsAgainst": 17
   },
   "Panthers-L": {
    "result": "L",
    "pointsFor": 17,
    "pointsAgainst": 20
   },
   "Broncos-W": {
    "result": "W",
    "pointsFor": 20,
    "pointsAgainst": 17
   },
   "Jaguars-L": {
    "result": "W",
    "pointsFor": 20,
    "pointsAgainst": 17
   },
   "Ravens-W": {
    "result": "L",
    "pointsFor": 17,
    "pointsAgainst": 20
   },
   "Texans-W": {
    "result": "L",
    "pointsFor": 17,
    "pointsAgainst": 20
   },
   "Titans-L": {
    "result": "L",
    "pointsFor": 17,
    "pointsAgainst": 20
   },
   "Cowboys-L": {
    "result": "L",
    "pointsFor": 17,
    "pointsAgainst": 20
   },
   "Dolphins-L": {
    "result": "L",
    "pointsFor": 17,
    "pointsAgainst": 20
   },
   "Chiefs-W": {
    "result": "L",
    "pointsFor": 17,
    "pointsAgainst": 20
   },
   "Jets-L": {
    "result": "L",
    "pointsFor": 17,
    "pointsAgainst": 20
   },
   "Bengals-W": {
    "result": "W",
    "pointsFor": 20,
    "pointsAgainst": 17
   },
   "Packers-W": {
    "result": "W",
    "pointsFor": 20,
    "pointsAgainst": 17
   },
   "Falcons-L": {
    "result": "L",
    "pointsFor": 17,
    "pointsAgainst": 20
   },
   "Lions-W": {
    "result": "L",
    "pointsFor": 17,
    "pointsAgainst": 20
   },
   "Browns-L": {
    "result": "L",
    "pointsFor": 17,
    "pointsAgainst": 20
   },
   "Chargers-W": {
    "result": "W",
    "pointsFor": 20,
    "pointsAgainst": 17
   },
   "Raiders-L": {
    "result": "W",
    "pointsFor": 20,
    "pointsAgainst": 17
   },
   "Falcons-W": {
    "result": "L",
    "pointsFor": 17,
    "pointsAgainst": 20
   },
   "Commanders-W": {
    "result": "W",
    "pointsFor": 20,
    "pointsAgainst": 17
   },
   "Saints-L": {
    "result": "L",
    "pointsFor": 17,
    "pointsAgainst": 20
   },
   "Buccaneers-W": {
    "result": "W",
    "pointsFor": 20,
    "pointsAgainst": 17
   },
   "Rams-W": {
    "result": "W",
    "pointsFor": 20,
    "pointsAgainst": 17
   },
   "Cardinals-L": {
    "result": "W",
    "pointsFor": 20,
    "pointsAgainst": 17
   }
  },
  "expectedTotals": {
   "duriez": 4,
   "alec": 3,
   "joe": 3,
   "cummiskey": 4,
   "little": 2,
   "corley": 4
  },
  "mendoza": 3.3333333333333335
 }
};
