#!/usr/bin/env python3
"""Turn a games file into an app-importable season state.

    python3 tools/build_season.py data/2025-games.json --out data/2025-season.json \
        --skip-week 1

Maps each draft pick in js/league.js onto that NFL team's real result for every
week. --skip-week leaves a week with no entries, which is how the 2025 archive
records that the league did not play Week 1.
"""

import argparse
import json
import os
import re

WEEK_IDS = [str(i) for i in range(1, 19)] + ["WC", "DIV", "CC", "SB"]


def read_league(path):
    """A league exported from the Draft Setup screen, or the legacy js/league.js."""
    if path.endswith(".json"):
        doc = json.load(open(path))
        return {"teams": doc["teams"], "picks": doc["picks"]}

    src = open(path).read()
    teams = [
        {"id": tid, "name": name, "members": [m.strip().strip("'") for m in members.split(",")]}
        for tid, name, members in re.findall(
            r"\{ id: '(\w+)', name: '([^']+)', members: \[([^\]]+)\] \}", src
        )
    ]
    picks = []
    for tid, nfl, direction, pick_no in re.findall(
        r"\['(\w+)', '([\w/ ]+)', '([WL])', (\d+)\]", src
    ):
        pick_no = int(pick_no)
        picks.append(
            {
                "id": f"{nfl}-{direction}",
                "teamId": tid,
                "nflTeam": nfl,
                "direction": direction,
                "pickNo": pick_no,
                "round": (pick_no - 1) // len(teams) + 1,
            }
        )
    return {"teams": teams, "picks": picks}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("games")
    parser.add_argument("--out", required=True)
    parser.add_argument("--league", default="js/league.js")
    parser.add_argument("--skin-value", type=float, default=100)
    parser.add_argument("--skip-week", action="append", default=[])
    parser.add_argument("--fixture", help="also emit the state as an importable .mjs for tests")
    parser.add_argument(
        "--overrides",
        help="optional corrections applied on top of the pulled results, so re-running never clobbers them",
    )
    args = parser.parse_args()


    games_doc = json.load(open(args.games))
    weeks = games_doc["weeks"]
    league = read_league(args.league)

    overrides = {}
    override_settings = {}
    if args.overrides and os.path.exists(args.overrides):
        doc = json.load(open(args.overrides))
        overrides = doc.get("weeks", {})
        override_settings = doc.get("settings", {})

    results = {}
    for week_id in WEEK_IDS:
        if week_id in args.skip_week:
            results[week_id] = {}
            continue
        week_games = weeks.get(week_id, {})
        entries = {}
        for pick in league["picks"]:
            game = week_games.get(pick["nflTeam"])
            if not game:
                continue  # bye, or the team was eliminated
            entries[pick["id"]] = {
                "result": game["result"],
                "pointsFor": game["pointsFor"],
                "pointsAgainst": game["pointsAgainst"],
            }
        # A manual correction wins over whatever the API said. Setting a pick to
        # null removes it, which is how you record "this game did not count".
        for pick_id, entry in overrides.get(week_id, {}).items():
            if entry is None:
                entries.pop(pick_id, None)
            else:
                entries[pick_id] = entry
        results[week_id] = entries

    bonus_by_week = {w: True for w in WEEK_IDS}
    bonus_by_week.update(override_settings.get("bonusEnabledByWeek", {}))

    state = {
        "version": 2,
        "season": str(games_doc["season"]),
        "updated": games_doc.get("updated"),
        "settings": {
            "skinValue": override_settings.get("skinValue", args.skin_value),
            "bonusEnabledByWeek": bonus_by_week,
        },
        "league": league,
        "results": results,
    }
    with open(args.out, "w") as fh:
        json.dump(state, fh, indent=1, sort_keys=False)
        fh.write("\n")
    if args.fixture:
        with open(args.fixture, "w") as fh:
            fh.write("// Generated by tools/build_season.py. Do not edit by hand.\n")
            fh.write("export default ")
            json.dump(state, fh, indent=1, sort_keys=False)
            fh.write(";\n")
        print(f"wrote {args.fixture}")

    played = sum(1 for w in results.values() if w)
    print(f"wrote {args.out} ({played} weeks with results)")


if __name__ == "__main__":
    main()
